### PR TITLE
Fixing brain phantom values

### LINKED ISSUE #464: Brain phantom values inconsistencies
I found inconsistencies between `brain_phantom2D()` and the references provided. 

The current phantom definition holds:
-  The T2* value of MARROW is 70 ms, it should be 61 ms according to (Aubert-Broche, B. et al., 2006a)
- The PD value of SKIN/MUSCLE is 0.7, it should be 1 according to (Aubert-Broche, B. et al., 2006a)
- The T1 value of MUSCLE is 900 ms. According to (Aubert-Broche, B. et al., 2006a), it should be 0 ms, but according to (BrainWeb) it should be 900 ms. However, (BrainWeb) is not referenced in the documentation.

References
- Aubert-Broche, B., Alan C. Evans, and Louis Collins.  "A new improved version of the realistic digital brain phantom." NeuroImage 32, no. 1 (2006): 138-145. (Aubert-Broche, B. et al., 2006a)
- https://brainweb.bic.mni.mcgill.ca/brainweb/tissue_mr_parameters.txt (BrainWeb)

### PR DESCRIPTION
**Pull request by gsahonero**
This PR is to fix #464

### CODE REVIEW

File: KomaMRIBase/src/datatypes/Phantom.jl [hunk 1]
```diff
@@ -200,11 +200,16 @@ Creates a two-dimensional brain Phantom struct.
...
+-  Aubert-Broche, B., Alan C. Evans, and Louis Collins. 
+    "A new improved version of the realistic digital brain phantom." NeuroImage 32, no. 1 (2006): 138-145. (Aubert-Broche, B. et al., 2006a)
+- Aubert-Broche, B., Mark Griffin, G. Bruce Pike, Alan C. Evans, and D. Louis Collins. 
+    "Twenty new digital brain phantoms for creation of validation image data bases." IEEE transactions on medical imaging 25, no. 11 (2006): 1410-1416. (Aubert-Broche, B. et al., 2006b)
+- https://brainweb.bic.mni.mcgill.ca/brainweb/tissue_mr_parameters.txt (BrainWeb)
+
+## Reproducibility notes
+- T1, T2, T2* and PD Values for CSF, GM, WM, FAT, MUSCLE, SKIN/MUSCLE, SKULL, VESSELS, FAT2, DURA, MARROW are extracted from (Aubert-Broche, B. et al., 2006a)
+- The T1 value for muscle is extracted from (Brainweb) as (Aubert-Broche, B. et al., 2006a) reports a 00 value. 
+- The T1 value of SKIN/MUSCLE is different between (BrainWeb) and (Aubert-Broche, B. et al., 2006a), we used the latter one.
```
Comment (cncastillo) [inline KomaMRIBase/src/datatypes/Phantom.jl:212]: Remove "Reproducibilty notes". Do not modify previous citations; just add more specific link to brainweb parameters.

**Review by cncastillo — CHANGES_REQUESTED** [review]
Brainweb is already referenced in the documentation:

> Creates a three-dimentional brain Phantom struct. Default ss=4 sample spacing is 2 mm. Original file (ss=1) sample spacing is .5 mm.
> 
> References
> 
>     B. Aubert-Broche, D.L. Collins, A.C. Evans: "A new improved version of the realistic digital brain phantom" NeuroImage, in review - 2006
>     B. Aubert-Broche, M. Griffin, G.B. Pike, A.C. Evans and D.L. Collins: "20 new digital brain phantoms for creation of validation image data bases" IEEE TMI, in review - 2006
>     https://brainweb.bic.mni.mcgill.ca/brainweb

These are the parameters I used (Aubert-Broche, B. et al., 2006a)

https://github.com/JuliaHealth/KomaMRI.jl/blob/v0.1-alpha/src/data/Brain2DParameters.png
image

The 00 for the muscle must be a typo in the table. The skin value I could have changed on purpose (see JEMRIS's brain phantom).

Please check that phantom3D also has these changes.

**Review by gsahonero — COMMENTED** [review]
Updates according to requested changes.

**Review by cncastillo — APPROVED** [review]
